- name: Configure webserver with nginx
  hosts: webservers
  become: True
  vars:
    - key_file: /etc/nginx/ssl/nginx.key
    - cert_file: /etc/nginx/ssl/nginx.crt
    - conf_file: /etc/nginx/sites-available/default
    - server_name: localhost
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: create dirs for ssl
      file: path=/etc/nginx/ssl state=directory

    - name: Copy TLS Key
      copy: src=files/nginx.key dest={{key_file}} owner=root mode=0600
      notify: restart nginx

    - name: copy TLS certificate
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx 

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: restart nginx
      service: name=nginx state=restarted

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted